# Generated by Django 4.2.6 on 2023-11-16 15:48

from django.db import migrations, models
from spacare.danh_muc.models import DanhMuc


def migrate_danh_muc(apps, schema_editor):
    data = [
        {
            "ten_danh_muc": "Dịch vụ",
            "the_loai_danh_muc": "Massage",
        },
        {
            "ten_danh_muc": "Dịch vụ",
            "the_loai_danh_muc": "Chăm sóc da mặt",
        },
        {
            "ten_danh_muc": "Dịch vụ",
            "the_loai_danh_muc": "Chăm sóc cơ thể",
        },
        {
            "ten_danh_muc": "Dịch vụ",
            "the_loai_danh_muc": "Chăm sóc móng",
        },
        {
            "ten_danh_muc": "Dịch vụ",
            "the_loai_danh_muc": "Dịch vụ Tóc",
        },
        {
            "ten_danh_muc": "Dịch vụ",
            "the_loai_danh_muc": "Dịch vụ Tóc",
        },
        {
            "ten_danh_muc": "Sản phẩm",
            "the_loai_danh_muc": "Chăm sóc da mặt",
        },
        {
            "ten_danh_muc": "Sản phẩm",
            "the_loai_danh_muc": "Chăm sóc cơ thể",
        },
        {
            "ten_danh_muc": "Sản phẩm",
            "the_loai_danh_muc": "Chăm sóc tóc",
        },
    ]
    list_danh_muc = []
    for item in data:
        list_danh_muc.append(
            DanhMuc(
                ten_danh_muc=item["ten_danh_muc"],
                the_loai_danh_muc=item["the_loai_danh_muc"],
            )
        )
    DanhMuc.objects.bulk_create(list_danh_muc)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DanhMuc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_danh_muc", models.CharField(max_length=255)),
                ("the_loai_danh_muc", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(migrate_danh_muc),
    ]
