# Generated by Django 4.2.6 on 2023-12-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dich_vu", "0001_initial"),
        ("lich_hen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChiTietLichHen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dich_vu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dich_vu.dichvu"
                    ),
                ),
                (
                    "lich_hen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lich_hen.lichhen",
                    ),
                ),
            ],
        ),
    ]
