# Generated by Django 4.2.6 on 2023-12-06 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lich_hen", "0002_remove_lichhen_dich_vu"),
        ("dich_vu", "0001_initial"),
        ("chi_tiet_lich_hen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitietlichhen",
            name="dich_vu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chi_tiet_lich_hen_dich_vu",
                to="dich_vu.dichvu",
            ),
        ),
        migrations.AlterField(
            model_name="chitietlichhen",
            name="lich_hen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chi_tiet_lich_hen",
                to="lich_hen.lichhen",
            ),
        ),
    ]
