# Generated by Django 4.2.6 on 2023-12-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chi_tiet_lich_hen", "0002_alter_chitietlichhen_dich_vu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chitietlichhen",
            name="ghi_chu",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chitietlichhen",
            name="trang_thai",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
