# Generated by Django 4.2.6 on 2023-12-22 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chi_tiet_lich_hen", "0003_chitietlichhen_ghi_chu_chitietlichhen_trang_thai"),
    ]

    operations = [
        migrations.AddField(
            model_name="chitietlichhen",
            name="nhan_vien",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nhan_vien_lam",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
