# Generated by Django 4.2.6 on 2023-12-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chi_tiet_lich_hen", "0004_chitietlichhen_nhan_vien"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitietlichhen",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("Chưa Hoàn Thành", "chua_hoan_thanh"),
                    ("Đang Hoàn Thành", "dang_hoan_thanh"),
                    ("Đã hoàn thành", "da_hoan_thanh"),
                ],
                default="Chưa Hoàn Thành",
                max_length=255,
            ),
        ),
    ]
