# Generated by Django 4.2.6 on 2023-12-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chi_tiet_lich_hen", "0005_alter_chitietlichhen_trang_thai"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chitietlichhen",
            name="ghi_chu",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
