# Generated by Django 4.2.6 on 2023-12-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("san_pham", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sanpham",
            name="hinh_anh",
            field=models.TextField(null=True),
        ),
    ]
