# Generated by Django 4.2.6 on 2023-11-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("danh_muc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DichVu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hinh_anh", models.CharField(max_length=255, null=True)),
                ("ten_dich_vu", models.CharField(max_length=255)),
                ("mo_ta", models.CharField(max_length=255, null=True)),
                ("gia", models.BigIntegerField(default=0)),
                ("thoi_gian_thuc_hien", models.IntegerField(default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "danh_muc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="danh_muc.danhmuc",
                    ),
                ),
            ],
        ),
    ]
