# Generated by Django 4.2.6 on 2024-01-05 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dich_vu", "0004_alter_dichvu_hinh_anh"),
        ("combo", "0002_combo_hinh_anh"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChiTietCombo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chi_tiet_combo",
                        to="combo.combo",
                    ),
                ),
                (
                    "dich_vu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combo_dich_vu",
                        to="dich_vu.dichvu",
                    ),
                ),
            ],
        ),
    ]
