# Generated by Django 4.2.6 on 2023-11-20 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dich_vu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LichHen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thoi_gian_hen", models.DateTimeField()),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("Chưa Duyệt", "chua_duyet"),
                            ("Đã Duyệt", "da_duyet"),
                        ],
                        default="Chưa Duyệt",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dich_vu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dich_vu.dichvu"
                    ),
                ),
                (
                    "khach_hanh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="khach_hang",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nhan_vien",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nhan_vien",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
