# Generated by Django 4.2.6 on 2023-12-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uu_dai", "0001_initial"),
        ("lich_hen", "0002_remove_lichhen_dich_vu"),
    ]

    operations = [
        migrations.AddField(
            model_name="lichhen",
            name="tien_coc",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="lichhen",
            name="tong_tien",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="lichhen",
            name="uu_dai",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uu_dai",
                to="uu_dai.uudai",
            ),
        ),
    ]
