# Generated by Django 4.2.6 on 2023-12-22 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lich_hen", "0003_lichhen_tien_coc_lichhen_tong_tien_lichhen_uu_dai"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lichhen",
            name="nhan_vien",
        ),
    ]
